# .travis.yml for a TypeScript backend project

language: node_js

node_js:
  - "14"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm test
  - npm run test:coverage

# Optional: Set environment variables for the deployment
env:
  - NODE_ENV=development

after_success:
  - echo "Build passed!"
  - codecov